#### NOTES:
### =>  Brand can be brand or subsidiary
###
#####

#####
# Bottlecap.create(drink: "", brand: "", parent: "", favorite: false, cap_detail_list: "", pinned: false, notes: nil)
#####

Bottlecap.create(drink: "Am I Right or Amarillo", brand: "Bell's Brewery", parent: "Bell's Brewery", favorite: false, cap_detail_list: "orange, cowboy hat", pinned: false)
Bottlecap.create(drink: "Amber Ale", brand: "Bell's Brewery", parent: "Bell's Brewery", favorite: false, cap_detail_list: "red, maroon, heron, bird", pinned: false)
Bottlecap.create(drink: "Pale Ale", brand: "Omission Beer", parent: "Omission Beer", favorite: false, cap_detail_list: "blue, black, big letter, O", pinned: false)
Bottlecap.create(drink: "Sangria Soda", brand: "Topo Chico", parent: "Topo Chico", favorite: false, cap_detail_list: "purple, silver, grapes", pinned: false)
Bottlecap.create(drink: "Palma Louca", brand: "Cerveja Brasil", parent: "Cerveja Brasil", favorite: false, cap_detail_list: "blue, gold", pinned: false)
Bottlecap.create(drink: "Pineapple Soda", brand: "Fanta", parent: "The Coca-Cola Company", favorite: false, cap_detail_list: "yellow", pinned: false)
Bottlecap.create(drink: "Virgil's Root Beer", brand: "Virgil's", parent: "Reed's", favorite: false, cap_detail_list: "white, gold, red", pinned: false)
Bottlecap.create(drink: "Summer Shandy", brand: "Jacob Leinenkugel Brewing Company", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "light blue, lemon", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Seagram's", parent: "Diageo", favorite: false, cap_detail_list: "blue, palm trees", pinned: false)
Bottlecap.create(drink: "Session Black Lager", brand: "Full Sail Brewing Company", parent: "Full Sail Brewing Company", favorite: false, cap_detail_list: "dark blue, dark gray, diamond", pinned: false)
Bottlecap.create(drink: "Old Speckled Hen", brand: "Morland Brewery", parent: "Greene King Brewery", favorite: false, cap_detail_list: "red, gold", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Woodchuck Hard Cider", parent: "Vermont Hard Cider Company", favorite: false, cap_detail_list: "black, white", pinned: false)
Bottlecap.create(drink: "Pale 31", brand: "Firestone Walker Brewing Company", parent: "Duvel Moortgat Brewery", favorite: false, cap_detail_list: "yellow, California", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Ninkasi Brewing Company", parent: "Ninkasi Brewing Company", favorite: false, cap_detail_list: "black, blue, teal, big letter", pinned: false)
Bottlecap.create(drink: "Summer Ale", brand: "Samuel Adams", parent: "Boston Brewing Company", favorite: false, cap_detail_list: "yellow, orange", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Squatters Craft Beer", parent: "Utah Brewers Cooperative", favorite: false, cap_detail_list: "beige, silver, circle, 1989", pinned: false)
Bottlecap.create(drink: "IPA", brand: "Omission Beer", parent: "Omission Beer", favorite: false, cap_detail_list: "green, black, big letter, O", pinned: false)
Bottlecap.create(drink: "Michelob Ultra Lime Cactus", brand: "Michelob", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "white, green", pinned: false)
Bottlecap.create(drink: "Harvest Patch Shandy", brand: "Jacob Leinenkugel Brewing Company", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "orange, white, pumpkin", pinned: false)
Bottlecap.create(drink: "Smith & Forge Hard Cider", brand: "Smith & Forge", parent: "MillerCoors", favorite: false, cap_detail_list: "orange, black, hammer", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "New Planet Beer Company", parent: "New Planet Brewery", favorite: false, cap_detail_list: "green, white", pinned: false)
Bottlecap.create(drink: "Revive Rootbeer", brand: "LIVE Kombucha Soda", parent: "LIVE Soda", favorite: false, cap_detail_list: "brown, white, red", pinned: false)
Bottlecap.create(drink: "Oktoberfest", brand: "Jacob Leinenkugel Brewing Company", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "blue, white, checkerboard", pinned: false)
Bottlecap.create(drink: "Root Beer", brand: "Best Damn Brewing Company", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "brown, white, black", pinned: false)
Bottlecap.create(drink: "Spaten Lager", brand: "Spaten", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "white, shovel, red", pinned: false)
Bottlecap.create(drink: "IPA", brand: "Odell Brewing Company", parent: "Odell Brewing Company", favorite: false, cap_detail_list: "orange, white, leaf, hops", pinned: false)
Bottlecap.create(drink: "Draft Cider", brand: "Newton's Folly", parent: "Vermont Hard Cider Company", favorite: false, cap_detail_list: "black, white, apple", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Funkwerks", parent: "Funkwerks", favorite: false, cap_detail_list: "black, silver, circle, fw", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Elysian Brewing Company", parent: "Elysian Brewing Company", favorite: false, cap_detail_list: "black, gold, leaf, hops", pinned: false)
Bottlecap.create(drink: "Longboard Island Ale", brand: "Kona Brewing Company", parent: "Craft Brew Alliance", favorite: false, cap_detail_list: "red, white, lizard", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: nil, parent: nil, favorite: false, cap_detail_list: "gold", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Shock Top", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "red, maroon, wheat", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Maredsous", parent: "Duvel Moortgat Brewery", favorite: false, cap_detail_list: "blue, gold, hexagon", pinned: false)
Bottlecap.create(drink: "Southern Peach Ginger Ale", brand: "Fest Cola", parent: "Fest Cola", favorite: false, cap_detail_list: "white, silver, circle, Flavor is our Birthright", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Leibinger Brewery", parent: "Leibinger Brewery", favorite: false, cap_detail_list: "white, red, black, crown, crest", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Firestone Walker Brewing Company", parent: "Duvel Moortgat Brewery", favorite: false, cap_detail_list: "black, gold, fighting, bear", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: nil, parent: nil, favorite: false, cap_detail_list: "black", pinned: false)
Bottlecap.create(drink: "LandShark Lager", brand: "Margaritaville Brewing Company", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "yellow, blue, shark, fin, palm trees", pinned: false)
Bottlecap.create(drink: "Strawberry Ale", brand: "Redd's", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "green, black, gold, shield, big letter, R", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Saranac Brewery", parent: "Matt Brewing Company", favorite: false, cap_detail_list: "gold, yellow, 1888, circle, white", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Stone Brewing", parent: "Stone Brewing", favorite: false, cap_detail_list: "gold, black, devil, 20, anniversary", pinned: false)
Bottlecap.create(drink: "Sparkling Apple", brand: "Izze", parent: "", favorite: false, cap_detail_list: "light green, silver, flower", pinned: false)
Bottlecap.create(drink: "Blonde", brand: "Affligem Brewery", parent: "Heineken International", favorite: false, cap_detail_list: "beige, black, red, shield", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Lindemans Brewery", parent: "Lindemans Brewery", favorite: false, cap_detail_list: "gold, brown, anno, 1822, oversized", pinned: false)
Bottlecap.create(drink: "Cherry Cola", brand: "Best Damn Brewing Company", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "maroon, white, black, circle", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Ceramico Alfredo Gioventù Portofino", parent: "Ceramico Alfredo Gioventù Portofino", favorite: false, cap_detail_list: "white, yellow, red, Jesus, fish", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Woodchuck Hard Cider", parent: "Vermont Hard Cider Company", favorite: false, cap_detail_list: "black, white, circle", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Squatters Craft Beer", parent: "Utah Brewers Cooperative", favorite: false, cap_detail_list: "beige, silver", pinned: false)
Bottlecap.create(drink: "Texas Amber", brand: "ZiegenBock Brewing Company", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "black, red, circle, kinda legendary, Z", pinned: false)
Bottlecap.create(drink: "Session Wheat", brand: "Full Sail Brewing Company", parent: "Full Sail Brewing Company", favorite: false, cap_detail_list: "yellow, black, diamond", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Deschutes Brewery", parent: "Deschutes Brewery", favorite: false, cap_detail_list: "oval, mountains, river, bend, ore, maroon", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: nil, parent: nil, favorite: false, cap_detail_list: "big letter, M, dragons, blue, gold", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Harpoon Brewery", parent: "Harpoon Brewery", favorite: false, cap_detail_list: "big letter, H, square, diamond, red, white", pinned: false)
Bottlecap.create(drink: "Beck's", brand: "Beck's Brewery", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "silver, red, black, stripe, crest, key, pry off", pinned: false)
Bottlecap.create(drink: "Coors Light", brand: "Coors Brewing Company", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "mountains, circle, silver, gray, 1978, born in the Rockies", pinned: false)
Bottlecap.create(drink: "Pilsner", brand: "Joseph's Brau Brewing Company", parent: "Trader Joe's Brewing Company", favorite: false, cap_detail_list: "red, pink, blue, white, JB, circle, light blue", pinned: false, notes: nil)
Bottlecap.create(drink: "Strawberry Soda", brand: "Fanta", parent: "The Coca-Cola Company", favorite: false, cap_detail_list: "red, blue, white", pinned: false, notes: nil)
Bottlecap.create(drink: "Unspecified", brand: "LIVE Kombucha Soda", parent: "LIVE Soda", favorite: false, cap_detail_list: "white, red", pinned: false)
Bottlecap.create(drink: "Rolling Rock", brand: "Rolling Rock", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "silver, blue, horse, circle", pinned: true, notes: nil)
Bottlecap.create(drink: "Cranberry Ale", brand: "Redd's", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "red, gold, limited pick", pinned: false)
Bottlecap.create(drink: "Pilsener", brand: "Cerveceria La Constancia S.A.", parent: "Cerveceria La Constancia S.A.", favorite: true, cap_detail_list: "gold, red, white, circle, ace of hearts", pinned: false, notes: "Possibly my #1 favorite bottlecap")
Bottlecap.create(drink: "Unspecified", brand: "Johnnie Ryan Beverage Company", parent: "Johnnie Ryan Beverage Company", favorite: true, cap_detail_list: "top hat, magic wand, cirlcle, white, red", pinned: false, notes: "Looks kind of metallic, but that might be in my head")
Bottlecap.create(drink: "Festivity Ale", brand: "Goose Island Beer Company", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "black, white, yellow, circle, gold", pinned: false, notes: nil)
Bottlecap.create(drink: "Bock", brand: "Shiner", parent: "Spoetzl Brewery", favorite: false, cap_detail_list: "red, yellow, ram, circle", pinned: true, notes: "A classic.")
Bottlecap.create(drink: "The Anvil", brand: "Sonoma Cider", parent: "Sonoma Beverage Works", favorite: true, cap_detail_list: "orange, black, circle", pinned: false, notes: nil)
Bottlecap.create(drink: "The Pitchfork", brand: "Sonoma Cider", parent: "Sonoma Beverage Works", favorite: true, cap_detail_list: "green, black, circle", pinned: false, notes: nil)
Bottlecap.create(drink: "Cream Soda", brand: "IBC", parent: "Dr Pepper Snapple Group", favorite: false, cap_detail_list: "red, gold", pinned: false, notes: nil)
Bottlecap.create(drink: "Unspecified", brand: "Fizzy Lizzy", parent: "White Rock Beverages", favorite: true, cap_detail_list: "white, silver, twist off", pinned: true, notes: nil)
Bottlecap.create(drink: "Unspecified", brand: "ONLI Beverage", parent: "ONLI Beverage", favorite: false, cap_detail_list: "dark orange, white, twist off", pinned: false, notes: nil)
Bottlecap.create(drink: "Bud Light", brand: "Budweiser", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "blue, silver, red, curve", pinned: false, notes: "With the old, bad, bad branding.")
Bottlecap.create(drink: "Unspecified", brand: "KCCO", parent: "The Chive", favorite: true, cap_detail_list: "green, white, ostrich", pinned: false, notes: nil)
Bottlecap.create(drink: "Carta Blanca", brand: "Cuauhtémoc Moctezuma Brewery", parent: "Heineken International", favorite: false, cap_detail_list: "white, red, gold, oval, cerveza", pinned: false, notes: nil)
Bottlecap.create(drink: "White Wing", brand: "Shiner", parent: "Spoetzl Brewery", favorite: false, cap_detail_list: "orange, white, brown, bird", pinned: false, notes: nil)
Bottlecap.create(drink: "Sunset Wheat", brand: "Jacob Leinenkugel Brewing Company", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "blue, dark blue, gold, white, boat", pinned: false)
Bottlecap.create(drink: "Twisted Pretzel Wheat", brand: "Shock Top", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "black, brown, yellow", pinned: false, notes: "It's got a pretzel on it!")
Bottlecap.create(drink: "Non-Alcoholic Wheat", brand: "Erdinger Weissbrau", parent: "Erdinger Weissbrau", favorite: false, cap_detail_list: "blue, red, white, gold, wheat", pinned: false, notes: nil)
Bottlecap.create(drink: "Lager of the Lakes", brand: "Bell's Brewery", parent: "Bell's Brewery", favorite: false, cap_detail_list: "light blue, anchor, hops", pinned: false)
Bottlecap.create(drink: "Abt 12", brand: "St. Bernardus Brewery", parent: "St. Bernardus Brewery", favorite: false, cap_detail_list: "circle, blue, silver, 12", pinned: false, notes: nil)
Bottlecap.create(drink: "Lemon Ginger Cayenne", brand: "Brew Dr. Kombucha", parent: "Townhend's Tea Company", favorite: false, cap_detail_list: "orange, white, BDK, circle", pinned: false, notes: nil)
Bottlecap.create(drink: "Unspecified", brand: "Ninkasi Brewing Company", parent: "Ninkasi Brewing Company", favorite: false, cap_detail_list: "black, blue, teal, big letter", pinned: "This one features an even bigger N than the other general Ninkasi cap.")
Bottlecap.create(drink: "Oatsmobile Ale", brand: "Bell's Brewery", parent: "Bell's Brewery", favorite: false, cap_detail_list: "brown, horse head", pinned: false, notes: "Older than the other Oatsmobile one, I believe")
Bottlecap.create(drink: "Strawberry Cider", brand: "Crown Valley Brewing", parent: "Crown Valley Brewing", favorite: false, cap_detail_list: "pink, gold, crown, leaf, wheat", pinned: false, notes: nil)
Bottlecap.create(drink: "Unspecified", brand: "Greenport Harbor Brewing Company", parent: "Greenport Harbor Brewing Company", favorite: false, cap_detail_list: "black, silver, big letter, circle, ripple", pinned: false, notes: nil)
Bottlecap.create(drink: "Unspecified", brand: "Ciderboys Hard Cider", parent: "Ciderboys Hard Cider", favorite: false, cap_detail_list: "maroon, white, circle", pinned: false, notes: "The \"Ciderboys\" on the cap has a birch tree look to it")
Bottlecap.create(drink: "Java Stout", brand: "Bell's Brewery", parent: "Bell's Brewery", favorite: false, cap_detail_list: "light blue, crazy coffee cup", pinned: false)
Bottlecap.create(drink: "Palm", brand: "Palm Brewery", parent: "Palm Brewery", favorite: false, cap_detail_list: "green, gold, horse, circle", pinned: false, notes: nil)
Bottlecap.create(drink: "Ginger", brand: "BAWLS Guarana", parent: "BAWLS Acquisition", favorite: false, cap_detail_list: "gold, white, basically all words", pinned: false, notes: nil)
Bottlecap.create(drink: "Toasted Lager", brand: "Blue Point Brewing Company", parent: "Anheuser-Busch InBev ", favorite: false, cap_detail_list: "blue, white, circle, buoy, ocean", pinned: false, notes: nil)
Bottlecap.create(drink: "White", brand: "Bira91", parent: "B9 Beverages", favorite: true, cap_detail_list: "red, gold, black, white circle, monkey", pinned: false, notes: "Got this one and the other Bira91 one from the back of a Westside Market learning about NYC's brewing scene. Shoutout to Martin")
Bottlecap.create(drink: "Blonde", brand: "Bira91", parent: "B9 Beverages", favorite: false, cap_detail_list: "light blue, gold, white circle, black, monkey", pinned: false, notes: nil)
Bottlecap.create(drink: "Smitten", brand: "Bell's Brewery", parent: "Bell's Brewery", favorite: false, cap_detail_list: "light blue, flower, daisy", pinned: false, notes: "Only one petal on there")
Bottlecap.create(drink: "Honey Robber", brand: "Blue Point Brewing Company", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "blue, white, circle, buoy, ocean", pinned: false, notes: nil)
Bottlecap.create(drink: "Goldbrau", brand: "Stiegl Brewery", parent: "Stiegl Brewery", favorite: false, cap_detail_list: "gold, white, red, stairs", pinned: false, notes: "Not really sure what the stair things are about")
Bottlecap.create(drink: "", brand: "Camden Town Brewery", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "black, white, red circle, castle tower", pinned: false, notes: nil)
# Bottlecap.create(drink: "", brand: "", parent: "", favorite: false, cap_detail_list: "", pinned: false, notes: nil)
