# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#####
# Bottlecap.create(drink: "", brand: "", unique: , tag_list: "")
#####

Bottlecap.create(drink: "Am I Right or Amarillo", brand: "Bell's Brewery", parent: "Bell's Brewery", unique: true, tag_list: "orange, cowboy hat")
Bottlecap.create(drink: "Amber Ale", brand: "Bell's Brewery", parent: "Bell's Brewery", unique: true, tag_list: "red, maroon, heron, bird")
Bottlecap.create(drink: "Pale Ale", brand: "Omission Beer", parent: "Omission Beer", unique: true, tag_list: "blue, black, O")
Bottlecap.create(drink: "Sangria Soda", brand: "Topo Chico", parent: "Topo Chico", unique: true, tag_list: "purple, grapes")
Bottlecap.create(drink: "Palma Louca", brand: "Cerveja Brasil", parent: "Cerveja Brasil", unique: true, tag_list: "blue, gold")
Bottlecap.create(drink: "Pineapple Soda", brand: "Fanta", parent: "Coca-Cola", unique: true, tag_list: "yellow")
Bottlecap.create(drink: "Virgil's Root Beer", brand: "Virgil's", parent: "Reed's", unique: false, tag_list: "white, gold, red")
Bottlecap.create(drink: "Summer Shandy", brand: "Jacon Leinenkugel Brewing Company", parent: "SABMiller", unique: true, tag_list: "light blue, lemon")
Bottlecap.create(drink: "Unspecified", brand: "Seagram's", parent: "Diageo", unique: false, tag_list: "blue, palm trees")
Bottlecap.create(drink: "Session Black Lager", brand: "Full Sail Brewing Company", parent: "Full Sail Brewing Company", unique: true, tag_list: "dark blue, dark gray")
Bottlecap.create(drink: "Old Speckled Hen", brand: "Morland Brewery", parent: "Greene King Brewery", unique: false, tag_list: "red, gold, Morland Brewery")
Bottlecap.create(drink: "Unspecified", brand: "Woodchuck Hard Cider", parent: "Vermont Hard Cider Company", unique: false, tag_list: "black")
Bottlecap.create(drink: "Pale 31", brand: "Firestone Walker Brewing Company", parent: "Duvel Moortgat Brewery", unique: true, tag_list: "yellow, California")
Bottlecap.create(drink: "Unspecified", brand: "Ninkasi Brewing Company", parent: "Ninkasi Brewing Company", unique: false, tag_list: "black, blue, teal, N")
Bottlecap.create(drink: "Summer Ale", brand: "Samuel Adams", parent: "Boston Brewing Company", unique: true, tag_list: "yellow, orange")
Bottlecap.create(drink: "Unspecified", brand: "Squatter's Craft Beer", parent: "Utah Brewers Collective", unique: false, tag_list: "cream, beige, silver")
Bottlecap.create(drink: "Omission IPA", brand: "Omission Beer", parent: "Omission Beer", unique: true, tag_list: "green, black, O")
Bottlecap.create(drink: "Michelob Ultra Lime Cactus", brand: "Michelob", parent: "Anheuser-Busch InBev", unique: true, tag_list: "white, green")
Bottlecap.create(drink: "Harvest Patch Shandy", brand: "Jacob Leinenkugel Brewing Company", parent: "SABMiller", unique: true, tag_list: "white, pumpkin")
Bottlecap.create(drink: "Smith & Forge Hard Cider", brand: "Smith & Forge", parent: "MillerCoors", unique: false, tag_list: "orange, black, hammer")
Bottlecap.create(drink: "Unspecified", brand: "New Planet Beer Company", parent: "New Planet Brewery", unique: false, tag_list: "green, white")
Bottlecap.create(drink: "Revive Rootbeer", brand: "LIVE Soda", parent: "LIVE Soda", unique: true, tag_list: "brown, white, red, live")
Bottlecap.create(drink: "Oktoberfest", brand: "Jacob Leinenkugel Brewing Company", parent: "SABMiller", unique: true, tag_list: "blue, white, checkerboard")
Bottlecap.create(drink: "Best Damn Root Beer", brand: "Best Damn Brewing Company", parent: "Anheuser-Busch InBev", unique: true, tag_list: "brown, white, black")
Bottlecap.create(drink: "Spaten Lager", brand: "Spaten", parent: "Anheuser-Busch InBev", unique: false, tag_list: "white, shovel, red")
Bottlecap.create(drink: "IPA", brand: "Odell Brewing Company", parent: "Odell Brewing Company", unique: true, tag_list: "orange, white, leaf, hops")
Bottlecap.create(drink: "Draft Cider", brand: "Newton's Folly", parent: "Vermont Hard Cider Company", unique: false, tag_list: "black, white, apple")
Bottlecap.create(drink: "Unspecified", brand: "Funkwerks", parent: "Funkwerks", unique: false, tag_list: "black, silver")
# Bottlecap.create(drink: "", brand: "", parent: "", unique: , tag_list: "")
# Bottlecap.create(drink: "", brand: "", parent: "", unique: , tag_list: "")
# Bottlecap.create(drink: "", brand: "", parent: "", unique: , tag_list: "")
# Bottlecap.create(drink: "", brand: "", parent: "", unique: , tag_list: "")
# Bottlecap.create(drink: "", brand: "", parent: "", unique: , tag_list: "")
# Bottlecap.create(drink: "", brand: "", parent: "", unique: , tag_list: "")
# Bottlecap.create(drink: "", brand: "", parent: "", unique: , tag_list: "")
# Bottlecap.create(drink: "", brand: "", parent: "", unique: , tag_list: "")
# Bottlecap.create(drink: "", brand: "", parent: "", unique: , tag_list: "")
# Bottlecap.create(drink: "", brand: "", parent: "", unique: , tag_list: "")
