# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#####
# Bottlecap.create(drink: "", brand: "", parent: "", favorite: false, cap_detail_list: "", pinned: false)
#####

Bottlecap.create(drink: "Am I Right or Amarillo", brand: "Bell's Brewery", parent: "Bell's Brewery", favorite: false, cap_detail_list: "orange, cowboy hat", pinned: false)
Bottlecap.create(drink: "Amber Ale", brand: "Bell's Brewery", parent: "Bell's Brewery", favorite: false, cap_detail_list: "red, maroon, heron, bird", pinned: false)
Bottlecap.create(drink: "Pale Ale", brand: "Omission Beer", parent: "Omission Beer", favorite: false, cap_detail_list: "blue, black, O", pinned: false)
Bottlecap.create(drink: "Sangria Soda", brand: "Topo Chico", parent: "Topo Chico", favorite: false, cap_detail_list: "purple, grapes", pinned: false)
Bottlecap.create(drink: "Palma Louca", brand: "Cerveja Brasil", parent: "Cerveja Brasil", favorite: false, cap_detail_list: "blue, gold", pinned: false)
Bottlecap.create(drink: "Pineapple Soda", brand: "Fanta", parent: "Coca-Cola", favorite: false, cap_detail_list: "yellow", pinned: false)
Bottlecap.create(drink: "Virgil's Root Beer", brand: "Virgil's", parent: "Reed's", favorite: false, cap_detail_list: "white, gold, red", pinned: false)
Bottlecap.create(drink: "Summer Shandy", brand: "Jacob Leinenkugel Brewing Company", parent: "SABMiller", favorite: false, cap_detail_list: "light blue, lemon", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Seagram's", parent: "Diageo", favorite: false, cap_detail_list: "blue, palm trees", pinned: false)
Bottlecap.create(drink: "Session Black Lager", brand: "Full Sail Brewing Company", parent: "Full Sail Brewing Company", favorite: false, cap_detail_list: "dark blue, dark gray", pinned: false)
Bottlecap.create(drink: "Old Speckled Hen", brand: "Morland Brewery", parent: "Greene King Brewery", favorite: false, cap_detail_list: "red, gold, Morland Brewery", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Woodchuck Hard Cider", parent: "Vermont Hard Cider Company", favorite: false, cap_detail_list: "black", pinned: false)
Bottlecap.create(drink: "Pale 31", brand: "Firestone Walker Brewing Company", parent: "Duvel Moortgat Brewery", favorite: false, cap_detail_list: "yellow, California", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Ninkasi Brewing Company", parent: "Ninkasi Brewing Company", favorite: false, cap_detail_list: "black, blue, teal, N", pinned: false)
Bottlecap.create(drink: "Summer Ale", brand: "Samuel Adams", parent: "Boston Brewing Company", favorite: false, cap_detail_list: "yellow, orange", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Squatter's Craft Beer", parent: "Utah Brewers Collective", favorite: false, cap_detail_list: "cream, beige, silver", pinned: false)
Bottlecap.create(drink: "Omission IPA", brand: "Omission Beer", parent: "Omission Beer", favorite: false, cap_detail_list: "green, black, O", pinned: false)
Bottlecap.create(drink: "Michelob Ultra Lime Cactus", brand: "Michelob", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "white, green", pinned: false)
Bottlecap.create(drink: "Harvest Patch Shandy", brand: "Jacob Leinenkugel Brewing Company", parent: "SABMiller", favorite: false, cap_detail_list: "white, pumpkin", pinned: false)
Bottlecap.create(drink: "Smith & Forge Hard Cider", brand: "Smith & Forge", parent: "MillerCoors", favorite: false, cap_detail_list: "orange, black, hammer", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "New Planet Beer Company", parent: "New Planet Brewery", favorite: false, cap_detail_list: "green, white", pinned: false)
Bottlecap.create(drink: "Revive Rootbeer", brand: "LIVE Soda", parent: "LIVE Soda", favorite: false, cap_detail_list: "brown, white, red, live", pinned: false)
Bottlecap.create(drink: "Oktoberfest", brand: "Jacob Leinenkugel Brewing Company", parent: "SABMiller", favorite: false, cap_detail_list: "blue, white, checkerboard", pinned: false)
Bottlecap.create(drink: "Best Damn Root Beer", brand: "Best Damn Brewing Company", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "brown, white, black", pinned: false)
Bottlecap.create(drink: "Spaten Lager", brand: "Spaten", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "white, shovel, red", pinned: false)
Bottlecap.create(drink: "IPA", brand: "Odell Brewing Company", parent: "Odell Brewing Company", favorite: false, cap_detail_list: "orange, white, leaf, hops", pinned: false)
Bottlecap.create(drink: "Draft Cider", brand: "Newton's Folly", parent: "Vermont Hard Cider Company", favorite: false, cap_detail_list: "black, white, apple", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Funkwerks", parent: "Funkwerks", favorite: false, cap_detail_list: "black, silver", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Elysian Brewing Company", parent: "Elysian Brewing Company", favorite: false, cap_detail_list: "black, gold, leaf, hops", pinned: false)
Bottlecap.create(drink: "Longboard Island Ale", brand: "Kona Brewing Company", parent: "Craft Brew Alliance", favorite: false, cap_detail_list: "red, white, lizard", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Unknown", parent: "Unknown", favorite: false, cap_detail_list: "gold", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Shock Top", parent: "Anheuser-Busch InBev", favorite: false, cap_detail_list: "red, maroon, wheat", pinned: false)
Bottlecap.create(drink: "Unspecified", brand: "Maredsous", parent: "Duvel Moortgat Brewery", favorite: false, cap_detail_list: "blue, gold, hexagon", pinned: false)
Bottlecap.create(drink: "", brand: "", parent: "", favorite: false, cap_detail_list: "", pinned: false)
# Bottlecap.create(drink: "", brand: "", parent: "", favorite: false, cap_detail_list: "", pinned: false)
# Bottlecap.create(drink: "", brand: "", parent: "", favorite: false, cap_detail_list: "", pinned: false)
# Bottlecap.create(drink: "", brand: "", parent: "", favorite: false, cap_detail_list: "", pinned: false)
# Bottlecap.create(drink: "", brand: "", parent: "", favorite: false, cap_detail_list: "", pinned: false)
# Bottlecap.create(drink: "", brand: "", parent: "", favorite: false, cap_detail_list: "", pinned: false)
# Bottlecap.create(drink: "", brand: "", parent: "", favorite: false, cap_detail_list: "", pinned: false)
# Bottlecap.create(drink: "", brand: "", parent: "", favorite: false, cap_detail_list: "", pinned: false)
# Bottlecap.create(drink: "", brand: "", parent: "", favorite: false, cap_detail_list: "", pinned: false)
# Bottlecap.create(drink: "", brand: "", parent: "", favorite: false, cap_detail_list: "", pinned: false)